#default parameters




default:
  rotations: {}
  parameters:
    exposure: -5
    resWidth: 640
    resHeight: 480
    framerate: 25
    codec: DIVX

#saved parameters    





saved:
  rotations:
    0: 90
    1: 90
    2: 90
    3: 270
  parameters:
    exposure: -9
    resWidth: 640
    resHeight: 480
    framerate: 30
    codec: H264
