"""Channel identity shared by recording and streaming serializers."""

from enum import StrEnum


class ChannelKind(StrEnum):
    KEYPOINTS_3D = "KEYPOINTS_3D"
    LANDMARKS_3D = "LANDMARKS_3D"
    SEGMENT_ORIGINS = "SEGMENT_ORIGINS"
    ROTATIONS_LOCAL = "ROTATIONS_LOCAL"
    ROTATIONS_WORLD = "ROTATIONS_WORLD"
    DERIVED_POINTS = "DERIVED_POINTS"
    JOINT_ANGLES = "JOINT_ANGLES"
    OVERLAY_2D = "OVERLAY_2D"
    SEGMENT_LENGTHS = "SEGMENT_LENGTHS"
    SEGMENT_SCALES = "SEGMENT_SCALES"
    MODEL_SCALE = "MODEL_SCALE"
    OVERLAY_REPROJECTIONS = "OVERLAY_REPROJECTIONS"
    TIMESTAMPS = "TIMESTAMPS"
    RAW_KEYPOINTS_3D = "RAW_KEYPOINTS_3D"
    TRIANGULATION_WEIGHTS = "TRIANGULATION_WEIGHTS"
