// AI-generated navigation configuration: 2026-09-10. Human review pending.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    ...['guides', 'architecture', 'development', 'notes', 'proposals'].map(dirName => ({
      type: 'category' as const,
      label: dirName.charAt(0).toUpperCase() + dirName.slice(1),
      items: [{type: 'autogenerated' as const, dirName}],
    })),
  ],
  workPlansSidebar: [{type: 'autogenerated', dirName: 'work-plans'}],
};

export default sidebars;
