name: Linting Flake8

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'freemocap/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.11"
      - name: Run noxfile
        run: |
          nox --session lint
